import {
  Ambulance,
  Armchair,
  Archive,
  ArrowLeft,
  ArrowRightLeft,
  ArrowDown,
  ArrowUp,
  Backpack,
  Baby,
  BadgeEuro,
  BadgePercent,
  Ban,
  BanknoteArrowDown,
  BanknoteArrowUp,
  BicepsFlexed,
  Beer,
  Bird,
  Bitcoin,
  Brain,
  Car,
  Camera,
  Calendar,
  CalendarPlus,
  Cannabis,
  CassetteTape,
  Cat,
  ChartLine,
  ChartPie,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleSmall,
  CircleX,
  Cigarette,
  Coffee,
  Coins,
  Copy,
  Cpu,
  CreditCard,
  DollarSign,
  Dog,
  Dumbbell,
  Ellipsis,
  Factory,
  Filter,
  FunnelX,
  Film,
  Fish,
  Footprints,
  Frown,
  GlassWater,
  Globe,
  Hamburger,
  Heart,
  HandCoins,
  House,
  Hospital,
  Laptop,
  LampDesk,
  Landmark,
  Leaf,
  LayoutDashboard,
  LibraryBig,
  LoaderCircle,
  Lock,
  type LucideIconData,
  Martini,
  Moon,
  Monitor,
  MountainSnow,
  MoveRight,
  Music4,
  Package,
  Pencil,
  PanelLeft,
  PiggyBank,
  Pill,
  Plus,
  Pizza,
  Popcorn,
  ReceiptText,
  Salad,
  Scale,
  Scissors,
  Search,
  Settings,
  ShoppingCart,
  Sparkles,
  Smile,
  Star,
  Store,
  Sun,
  Tag,
  Tags,
  Trash2,
  Tractor,
  TrainFront,
  TreePalm,
  Utensils,
  Vault,
  Wallet,
  Wrench,
  Refrigerator,
  X,
  Gamepad2,
  Gift,
  Glasses,
  Github,
  GraduationCap,
  School,
  Shirt,
} from 'lucide-angular';

export const ZARD_ICONS = {
  house: House,
  settings: Settings,
  search: Search,
  calendar: Calendar,
  'panel-left': PanelLeft,
  check: Check,
  x: X,
  circle: Circle,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-x': CircleX,
  'circle-small': CircleSmall,
  ban: Ban,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  'chevrons-up-down': ChevronsUpDown,
  'move-right': MoveRight,
  'arrow-right-left': ArrowRightLeft,
  'arrow-down': ArrowDown,
  'arrow-up': ArrowUp,
  'layout-dashboard': LayoutDashboard,
  'loader-circle': LoaderCircle,
  copy: Copy,
  ellipsis: Ellipsis,
  moon: Moon,
  monitor: Monitor,
  sun: Sun,
  pencil: Pencil,
  sparkles: Sparkles,
  heart: Heart,
  star: Star,
  popcorn: Popcorn,
  plus: Plus,
  'arrow-left': ArrowLeft,
  archive: Archive,
  lock: Lock,
  'calendar-plus': CalendarPlus,
  filter: Filter,
  'funnel-x': FunnelX,
  trash: Trash2,
  tag: Tag,
  'dollar-sign': DollarSign,
  'credit-card': CreditCard,
  ambulance: Ambulance,
  armchair: Armchair,
  backpack: Backpack,
  baby: Baby,
  'banknote-arrow-down': BanknoteArrowDown,
  'banknote-arrow-up': BanknoteArrowUp,
  beer: Beer,
  bitcoin: Bitcoin,
  'badge-euro': BadgeEuro,
  'badge-percent': BadgePercent,
  'biceps-flexed': BicepsFlexed,
  bird: Bird,
  camera: Camera,
  car: Car,
  cannabis: Cannabis,
  'cassette-tape': CassetteTape,
  cat: Cat,
  cigarette: Cigarette,
  coins: Coins,
  coffee: Coffee,
  cpu: Cpu,
  brain: Brain,
  dog: Dog,
  factory: Factory,
  footprints: Footprints,
  'hand-coins': HandCoins,
  scale: Scale,
  school: School,
  shirt: Shirt,
  smile: Smile,
  dumbbell: Dumbbell,
  film: Film,
  fish: Fish,
  frown: Frown,
  gift: Gift,
  'gamepad-2': Gamepad2,
  glasses: Glasses,
  github: Github,
  'graduation-cap': GraduationCap,
  'glass-water': GlassWater,
  globe: Globe,
  hamburger: Hamburger,
  'chart-line': ChartLine,
  'chart-pie': ChartPie,
  hospital: Hospital,
  'lamp-desk': LampDesk,
  laptop: Laptop,
  landmark: Landmark,
  leaf: Leaf,
  'library-big': LibraryBig,
  martini: Martini,
  'mountain-snow': MountainSnow,
  'music-4': Music4,
  package: Package,
  pizza: Pizza,
  'receipt-text': ReceiptText,
  salad: Salad,
  scissors: Scissors,
  'shopping-cart': ShoppingCart,
  store: Store,
  tags: Tags,
  tractor: Tractor,
  'train-front': TrainFront,
  pill: Pill,
  'piggy-bank': PiggyBank,
  'tree-palm': TreePalm,
  utensils: Utensils,
  vault: Vault,
  wallet: Wallet,
  wrench: Wrench,
  refrigerator: Refrigerator,
} as const satisfies Record<string, LucideIconData>;

export declare type ZardIcon = keyof typeof ZARD_ICONS | LucideIconData;
